using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace UIExample2
{
    public partial class MainMenu : Form
    {
        public MainMenu()
        {
            InitializeComponent();
        }

        private void MainMenu_Load(object sender, EventArgs e)
        {

        }

        private void btnAdd_Click(object sender, EventArgs e)
        {
            //generated by doble clicking on button
            AddForm addForm = new AddForm();    // create the form object
            addForm.StartPosition = FormStartPosition.CenterScreen;//enumeration example. hover over code
            addForm.ShowDialog();               //display form to user, must act on form
            //addForm.Show();                     //display for to user, can act on this form or main form
        }

        //generated by going to Events and double clicking in the Click field
        private void btnChange_Click(object sender, EventArgs e)
        {
            ChangeForm changeForm = new ChangeForm();
            changeForm.StartPosition = FormStartPosition.CenterScreen;
            changeForm.ShowDialog();

        }

        private void btnDelete_Click(object sender, EventArgs e)
        {
            DeleteForm deleteForm = new DeleteForm();
            deleteForm.StartPosition = FormStartPosition.CenterScreen;
            deleteForm.ShowDialog();
        }
    }
}
